"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from"next/link";import{useEffect,useState}from"react";import{Button,Card,Input,PageHeader,Textarea}from"@/components/ui/primitives";import{apiRequest}from"@/lib/api/client";import{isValidCareerFile}from"@/lib/utils";
type Resume={id:string;title:string;is_active:boolean;created_at:string};type Analysis={id:string;status:string;overall_score:number|null;created_at:string};
export function AnalysisHistory(){const[resumes,setResumes]=useState<Resume[]>([]);const[analyses,setAnalyses]=useState<Analysis[]>([]);const[error,setError]=useState("");useEffect(()=>{Promise.all([apiRequest<Resume[]>("/resumes"),apiRequest<Analysis[]>("/ats-analyses")]).then(([r,a])=>{setResumes(r);setAnalyses(a)}).catch((e:Error)=>setError(e.message))},[]);return <><PageHeader eyebrow="Resume intelligence" title="Resume library and analyses" description="Every item below is loaded from your account." action={<Link className="button button-primary" href="/resume-analysis/new">New upload</Link>}/>{error&&<p role="alert" className="field-error">{error}</p>}<div className="grid-2"><Card><h2>Resumes</h2>{resumes.length?resumes.map(r=><div className="suggestion" key={r.id}><strong>{r.title}</strong><span>{r.is_active?"Active":"Stored"}</span></div>):<p>No resumes uploaded.</p>}</Card><Card><h2>ATS analyses</h2>{analyses.length?analyses.map(a=><div className="suggestion" key={a.id}><strong>{a.overall_score==null?"No score":`${a.overall_score}/100`}</strong><span>{a.status}</span></div>):<p>No real analyses exist. The ATS engine is currently unavailable.</p>}</Card></div></>}
export function NewAnalysis(){const[title,setTitle]=useState("");const[file,setFile]=useState<File|null>(null);const[jd,setJd]=useState("");const[message,setMessage]=useState("");const[error,setError]=useState("");async function upload(){if(!file||!isValidCareerFile(file))return setError("Choose a PDF or DOCX no larger than 10 MB.");const body=new FormData();body.set("title",title||file.name);body.set("file",file);try{const result=await apiRequest<any>("/resumes",{method:"POST",body});setMessage(`Stored ${result.resume.title}. Review the extracted content before confirming it.`);setError("")}catch(e){setError((e as Error).message)}}async function addJd(){try{await apiRequest("/job-descriptions",{method:"POST",body:JSON.stringify({title:"Job description",raw_text:jd})});setMessage("Job description stored for review. No ATS score was generated.");setError("")}catch(e){setError((e as Error).message)}}return <><PageHeader eyebrow="Real document ingestion" title="Add resume and job evidence" description="Files are validated, stored privately, parsed deterministically, and marked for your review."/><div className="grid-2"><Card className="stack"><h2>Resume</h2><label className="field-label">Library title<Input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="field-label">PDF or DOCX<Input type="file" accept=".pdf,.docx" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><Button onClick={upload}>Upload resume</Button></Card><Card className="stack"><h2>Job description</h2><label className="field-label">Paste text<Textarea value={jd} onChange={e=>setJd(e.target.value)} /></label><Button disabled={!jd.trim()} onClick={addJd}>Store job description</Button></Card></div>{error&&<p role="alert" className="field-error">{error}</p>}{message&&<Card><p role="status">{message}</p></Card>}</>}
export function ExtractionReview(){return <><PageHeader eyebrow="Candidate review required" title="Review extracted content" description="Open a specific resume version from the library to edit and confirm its structured extraction."/><Card className="empty-state"><h2>Select a resume version</h2><p>This page never auto-confirms parsed content.</p><Link href="/resume-analysis">Return to library</Link></Card></>}
export function AtsReport(){return <><PageHeader eyebrow="ATS analysis" title="No generated report loaded" description="Reports display only after a real ATS engine persists evidence and a score."/><Card className="empty-state"><h2>Report unavailable</h2><p>No sample score or fabricated evidence is shown.</p></Card></>}
export function ResumeBuilder(){return <><PageHeader eyebrow="Resume versioning" title="Resume builder" description="Suggested edits require a persisted analysis and an explicit candidate decision."/><Card className="empty-state"><h2>No suggestions loaded</h2><p>The current backend deliberately returns an unavailable capability response instead of inventing edits.</p></Card></>}
