"use client";

import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { Check, ChevronRight, Download, Edit3, FileUp, History, Save, Sparkles, Undo2 } from "lucide-react";
import { Badge, Button, ButtonLink, Card, Input, PageHeader, Progress, Textarea } from "@/components/ui/primitives";
import { evidenceRows } from "@/data/demo-data";
import { isValidCareerFile } from "@/lib/utils";
import { useDemo } from "@/providers/demo-provider";

const stages = ["Reading documents", "Extracting sections", "Validating content", "Identifying requirements", "Matching evidence", "Calculating score", "Preparing explanation", "Complete"];
function useDemoAnalysis(active: boolean) { const [index, setIndex] = useState(0); useEffect(() => { if (!active || index >= stages.length - 1) return; const timer = window.setTimeout(() => setIndex((v) => v + 1), 360); return () => window.clearTimeout(timer); }, [active, index]); return index; }

export function AnalysisHistory() { return <><PageHeader eyebrow="Resume intelligence" title="Analysis history" description="Compare resume versions and job descriptions without losing the evidence behind each score." action={<ButtonLink href="/resume-analysis/new">New analysis</ButtonLink>} /><div className="grid-3"><Card><span className="badge badge-success">Complete</span><h2>78 / 100</h2><h3>Senior Product Analyst</h3><p>Northstar Labs · Resume v3</p><div className="cluster"><ButtonLink href="/resume-analysis/report/report-3" variant="secondary">View report</ButtonLink></div></Card><Card><span className="badge badge-info">Previous version</span><h2>72 / 100</h2><h3>Senior Product Analyst</h3><p>Northstar Labs · Resume v2</p><div className="cluster"><ButtonLink href="/resume-analysis/report/report-2" variant="secondary">Compare</ButtonLink></div></Card><Card className="panel-blue"><History size={36} /><h3>Version history is connected</h3><p>Every report records the resume version, job description, date, and evidence set used.</p></Card></div></>; }

export function NewAnalysis() {
  const router = useRouter(); const { state, dispatch } = useDemo(); const [resume, setResume] = useState(state.activeResume); const [jd, setJd] = useState("We are hiring a Senior Product Analyst to own SQL analysis, design experiments, build product dashboards, and present recommendations to executives. Experience with Amplitude is preferred."); const [error, setError] = useState("");
  const selectFile = (file?: File) => { if (!file) return; if (!isValidCareerFile(file)) { setError("Choose a PDF or DOCX file no larger than 10 MB."); return; } setError(""); setResume(file.name); };
  const continueFlow = () => { if (!resume || !jd.trim()) { setError("A resume and job description are required."); return; } dispatch({ type: "patch", value: { activeResume: resume, activeJobDescription: jd.slice(0, 64) } }); router.push("/resume-analysis/review"); };
  return <><PageHeader eyebrow="New analysis" title="Compare evidence, not assumptions." description="Choose a resume and job description. You will review extraction before any score appears." /><div className="grid-2"><Card><p className="eyebrow">1 · Resume</p><label className="dropzone"><FileUp size={40}/><strong>{resume || "Drop PDF or DOCX"}</strong><span>Browse · maximum 10 MB</span><Input className="sr-only" type="file" accept=".pdf,.docx" onChange={(e) => selectFile(e.target.files?.[0])} /></label><label className="field-label" style={{ marginTop: 18 }}>Or select a previous resume<select className="field" value={resume} onChange={(e) => setResume(e.target.value)}><option>Product Analyst Resume v3.pdf</option><option>Product Analyst Resume v2.pdf</option></select></label></Card><Card><p className="eyebrow">2 · Job description</p><div className="tabs"><button className="tab active">Paste text</button><button className="tab" type="button">Upload file</button><button className="tab" type="button">Previous</button></div><label className="field-label">Job description<Textarea value={jd} onChange={(e) => setJd(e.target.value)} /></label><p className="mono">{jd.length} characters</p></Card></div>{error && <p role="alert" className="field-error" style={{ marginTop: 20 }}>{error}</p>}<div className="cluster" style={{ justifyContent: "flex-end", marginTop: 24 }}><ButtonLink href="/resume-analysis" variant="secondary">Cancel</ButtonLink><Button onClick={continueFlow}>Review extraction <ChevronRight size={18}/></Button></div></>;
}

const resumeFields = [{ label: "Contact details", value: "Aarav Mehta · aarav@example.com · Bengaluru", status: "Available" },{ label: "Summary", value: "Product analyst with 3 years of experience turning behavioural data into decisions.", status: "Available" },{ label: "Skills", value: "SQL, Python, product analytics, data visualization", status: "Candidate corrected" },{ label: "Experience", value: "Product Analyst · Common Thread · 2023–present", status: "Available" },{ label: "Projects", value: "Retention cohort dashboard", status: "Low confidence" },{ label: "Education", value: "B.Tech, Information Technology", status: "Available" },{ label: "Certifications", value: "No certification text found", status: "Unavailable" }];
const jdFields = [{ label: "Role", value: "Senior Product Analyst", status: "Available" },{ label: "Company", value: "Northstar Labs", status: "Candidate corrected" },{ label: "Responsibilities", value: "Own SQL analysis, design experiments, build dashboards", status: "Available" },{ label: "Required skills", value: "Advanced SQL, product metrics, executive communication", status: "Available" },{ label: "Preferred skills", value: "Amplitude", status: "Low confidence" }];

export function ExtractionReview() { const router = useRouter(); const [active, setActive] = useState(false); const stage = useDemoAnalysis(active); useEffect(() => { if (active && stage === stages.length - 1) { const t = window.setTimeout(() => router.push("/resume-analysis/report/report-3"), 500); return () => window.clearTimeout(t); } }, [active, stage, router]); if (active) return <Card className="empty-state"><Sparkles size={44}/><p className="eyebrow">Demo analysis adapter</p><h1>{stages[stage]}</h1><Progress value={Math.round((stage + 1) / stages.length * 100)} label={`Stage ${stage + 1} of ${stages.length}`} /><p>Each stage is explicit and isolated so a real analysis API can replace this adapter.</p></Card>;
  return <><PageHeader eyebrow="Extraction review" title="Confirm the facts before scoring." description="Edit uncertain text and mark candidate corrections. No score is calculated on this page." /><div className="grid-2"><ExtractionGroup title="Resume extraction" fields={resumeFields} /><ExtractionGroup title="Job-description extraction" fields={jdFields} /></div><div className="cluster" style={{ justifyContent: "flex-end", marginTop: 24 }}><ButtonLink href="/resume-analysis/new" variant="secondary">Back</ButtonLink><Button onClick={() => setActive(true)}>Confirm and analyse</Button></div></>;
}
function ExtractionGroup({ title, fields }: { title: string; fields: typeof resumeFields }) { const [values, setValues] = useState(fields); return <Card><h2>{title}</h2><div className="stack">{values.map((field, index) => <label key={field.label} className="field-label"><div className="row"><span>{field.label}</span><Badge tone={field.status === "Available" ? "success" : field.status === "Unavailable" ? "danger" : "warning"}>{field.status}</Badge></div><Textarea value={field.value} onChange={(e) => setValues((all) => all.map((item, i) => i === index ? { ...item, value: e.target.value, status: "Candidate corrected" } : item))} /></label>)}</div></Card>; }

export function AtsReport() { const [saved, setSaved] = useState(false); const download = () => { const blob = new Blob(["Career Copilot demo ATS report\nScore: 78/100\nThis file contains frontend demo data only."], { type: "text/plain" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "career-copilot-demo-report.txt"; a.click(); URL.revokeObjectURL(url); };
  return <><PageHeader eyebrow="ATS report · Demo data" title="Strong foundation, with four focused improvements." description="Compared Product Analyst Resume v3 with Senior Product Analyst at Northstar Labs." action={<div className="cluster"><Button variant="secondary" onClick={() => setSaved(true)}><Save size={17}/>Save report</Button><Button onClick={download}><Download size={17}/>Download</Button></div>} />{saved && <div className="demo-banner" role="status">Report saved in this demo session.</div>}<div className="grid-2" style={{ marginTop: 24 }}><Card className="panel-blue"><div className="cluster"><div className="score-ring" aria-label="Overall ATS alignment score 78 out of 100">78</div><div><Badge tone="success">+6 from previous version</Badge><h2>Well aligned</h2><p>The resume covers the role’s core analytical requirements. Tool specificity and ownership language limit the score.</p></div></div></Card><Card><p className="eyebrow">Score breakdown</p><div className="stack">{[["Skills",84],["Experience",76],["Projects",72],["Education",90],["Semantic alignment",79],["Role alignment",83],["Structure",86],["Formatting",74],["Terminology coverage",68]].map(([label,value]) => <Progress key={label} label={String(label)} value={Number(value)} />)}</div></Card></div><div className="grid-3" style={{ marginTop: 24 }}><Card><Badge tone="success">Strengths</Badge><h3>Grounded analytical impact</h3><p>SQL, cohort analysis, KPI reporting, and cross-functional presentation have explicit resume evidence.</p></Card><Card><Badge tone="warning">Partial matches</Badge><h3>Experiment ownership</h3><p>The resume supports reporting, but does not clearly establish end-to-end experiment design.</p></Card><Card><Badge tone="danger">Not found</Badge><h3>Amplitude</h3><p>This skill was not found in the selected resume. Add it only if you can support the claim.</p></Card></div><section style={{ marginTop: 30 }}><div className="row"><div><p className="eyebrow">Requirement evidence</p><h2>Every match has a traceable basis.</h2></div></div><div className="table-wrap"><table><thead><tr><th>JD requirement</th><th>Resume evidence</th><th>Status</th><th>Contribution</th><th>Evidence type</th></tr></thead><tbody>{evidenceRows.map((row) => <tr key={row.requirement}><td><strong>{row.requirement}</strong></td><td>{row.evidence}</td><td><Badge tone={row.status === "Strong match" ? "success" : row.status === "Partial match" ? "warning" : "danger"}>{row.status}</Badge></td><td className="mono">{row.contribution}</td><td>{row.kind}</td></tr>)}</tbody></table></div></section><div className="panel panel-blue row" style={{ marginTop: 30 }}><div><h2>Turn evidence into the next version.</h2><p>Review suggested rewrites. Nothing is accepted automatically.</p></div><div className="cluster"><ButtonLink href="/resume-builder/demo">Improve resume</ButtonLink><ButtonLink href="/mock-interview/setup" variant="secondary">Start mock interview</ButtonLink></div></div></>;
}

const suggestions = [{ id: "s1", section: "Experience", original: "Supported A/B test reporting.", issue: "Ownership and method are unclear.", rewrite: "Analysed A/B test results and presented conversion trade-offs to product stakeholders.", evidence: "Existing role bullet and project notes" },{ id: "s2", section: "Summary", original: "Data-driven product analyst.", issue: "Generic positioning.", rewrite: "Product analyst using SQL and behavioural data to guide retention and growth decisions.", evidence: "Skills and two experience bullets" }];
export function ResumeBuilder() { const { state, dispatch } = useDemo(); const [current, setCurrent] = useState("Built cohort dashboards and supported A/B test reporting for product teams."); const [version, setVersion] = useState("Current draft"); return <><PageHeader eyebrow="Resume improvement" title="Improve claims without inventing them." description="Every rewrite is grounded in selected resume evidence and remains under your control." action={<div className="cluster"><Button variant="secondary"><Undo2 size={17}/>Undo</Button><Button><Save size={17}/>Save version</Button></div>} /><div className="editor-layout"><Card><p className="eyebrow">Sections</p><nav className="stack"><button className="tab active">Summary</button><button className="tab">Experience</button><button className="tab">Projects</button><button className="tab">Skills</button></nav><hr/><p className="eyebrow">Version history</p>{["Original", "Current draft", "Version 2"].map((v) => <button key={v} className={`tab ${version === v ? "active" : ""}`} onClick={() => setVersion(v)}>{v}</button>)}</Card><Card><div className="row"><div><Badge tone="info">{version}</Badge><h2>Experience</h2></div><span className="mono">Autosaved just now</span></div><label className="field-label">Role summary<Textarea value={current} onChange={(e) => setCurrent(e.target.value)} style={{ minHeight: 240 }} /></label><div className="cluster"><Badge tone="success">Changed text</Badge><span>“Analysed A/B test results”</span></div></Card><div className="stack"><Card className="panel-blue"><div className="row"><div><p className="eyebrow">Suggestions</p><h2>Evidence-based</h2></div><Sparkles /></div><p>Accept, edit, or reject. Suggested text never adds unsupported skills, numbers, or responsibilities.</p></Card>{suggestions.map((item) => <article key={item.id} className="suggestion"><div className="row"><Badge tone="ai">{item.section}</Badge>{state.suggestionDecisions[item.id] && <Badge tone={state.suggestionDecisions[item.id] === "accepted" ? "success" : "danger"}>{state.suggestionDecisions[item.id]}</Badge>}</div><strong>{item.issue}</strong><small>Original: {item.original}</small><p>{item.rewrite}</p><small>Supporting evidence: {item.evidence}</small><div className="cluster"><Button onClick={() => { setCurrent(item.rewrite); dispatch({ type: "suggestion", id: item.id, decision: "accepted" }); }}><Check size={16}/>Accept</Button><Button variant="secondary"><Edit3 size={16}/>Edit</Button><Button variant="quiet" onClick={() => dispatch({ type: "suggestion", id: item.id, decision: "rejected" })}>Reject</Button></div></article>)}</div></div></>; }
