"use client";

import { useState } from "react";
import { Bookmark, Check, CirclePlay, Clock, Target } from "lucide-react";
import { Badge, Button, ButtonLink, Card, PageHeader, Progress } from "@/components/ui/primitives";
import { learningItems } from "@/data/demo-data";
import { useDemo } from "@/providers/demo-provider";

export function LearningHome() { const { state } = useDemo(); return <><PageHeader eyebrow="Learning overview" title="Close the gaps that matter next." description="Recommendations connect to a specific ATS finding or interview observation; they are not generic course lists." /><div className="grid-4"><Card><span className="mono">Active paths</span><div className="metric-value">2</div><p>SQL readiness and answer structure</p></Card><Card><span className="mono">Weekly progress</span><div className="metric-value">3<small> items</small></div><p>One more than last week</p></Card><Card><span className="mono">Completed topics</span><div className="metric-value">{state.completedLearning.length}</div><p>Across active paths</p></Card><Card><span className="mono">Next topic</span><h3>Window functions</h3><p>From the SQL terminology gap</p></Card></div><div className="grid-2" style={{ marginTop: 28 }}><PathCard title="SQL Interview Readiness" progress={41} evidence="ATS gap: advanced SQL terminology" href="/learning/sql-readiness"/><PathCard title="Interview Answer Structure" progress={25} evidence="Interview: outcome and trade-off clarity" href="/learning/answer-structure"/></div></>; }
function PathCard({ title, progress, evidence, href }: { title: string; progress: number; evidence: string; href: string }) { return <Card className="panel-blue"><div className="row"><Target size={34}/><Badge tone="ai">Evidence-linked</Badge></div><h2>{title}</h2><p>{evidence}</p><Progress value={progress} label="Path progress"/><br/><ButtonLink href={href}>Continue path</ButtonLink></Card>; }

export function LearningPath({ pathId }: { pathId: string }) { const { state, dispatch } = useDemo(); const title = pathId.includes("answer") ? "Interview Answer Structure" : "SQL Interview Readiness"; return <><PageHeader eyebrow="Active learning path" title={title} description="An ordered sequence connected to your current career evidence." action={<Badge tone="info">Demo resources</Badge>} /><div className="grid-2"><Card><p className="eyebrow">Path sequence</p><ol className="stack">{["Fundamentals","Joins","Aggregations","Window functions","Query optimization","Interview exercises","Final assessment"].map((item,i)=><li key={item} className="suggestion"><span className="mono">0{i+1}</span><strong>{item}</strong></li>)}</ol></Card><div className="stack">{learningItems.map((item) => { const done = state.completedLearning.includes(item.id); return <Card key={item.id}><div className="row"><Badge tone={done ? "success" : "info"}>{done ? "Complete" : item.type}</Badge><span className="cluster"><Clock size={16}/>{item.duration}</span></div><h2>{item.title}</h2><p>{item.objective}</p><small>Why recommended: reinforces the ATS requirement for advanced SQL.</small><div className="cluster" style={{ marginTop: 18 }}><Button onClick={() => dispatch({ type: "toggleLearning", id: item.id })}>{done ? <><Check size={17}/>Completed</> : <><CirclePlay size={17}/>Mark complete</>}</Button><Button variant="secondary"><Bookmark size={17}/>Save</Button>{item.id === "window-functions" && <ButtonLink href="/learning/topic/window-functions" variant="quiet">Open topic</ButtonLink>}</div></Card>; })}</div></div></>; }

export function TopicPage({ topicId }: { topicId: string }) { const { state, dispatch } = useDemo(); const [answer, setAnswer] = useState(""); const [checked, setChecked] = useState(false); const complete = state.completedLearning.includes(topicId); return <><PageHeader eyebrow="Learning topic" title={topicId.includes("answer") ? "Structuring evidence-rich answers" : "Window functions for product metrics"} description="Learn the concept, practise it, and record completion in your active path." /><div className="grid-2"><Card><h2>Learning objectives</h2><ul><li>Choose an appropriate analytical structure.</li><li>Explain the reasoning before the result.</li><li>Connect an example to the role requirement.</li></ul><h3>Prerequisites</h3><p>SQL joins and aggregations, or basic behavioural interview structure.</p><h3>Candidate notes</h3><textarea className="field" placeholder="Add private notes…" /></Card><Card className="panel-blue"><Badge tone="ai">Mini assessment</Badge><h2>Which approach best preserves row detail while calculating a cohort rank?</h2>{["A grouped aggregate only", "A window function over a partition", "A cross join without conditions"].map((option) => <label className="suggestion" key={option}><input type="radio" name="assessment" value={option} onChange={() => setAnswer(option)} />{option}</label>)}<Button disabled={!answer} onClick={() => setChecked(true)}>Check answer</Button>{checked && <p role="status"><strong>{answer.includes("window") ? "Correct." : "Review this topic."}</strong> A partitioned window keeps row-level context.</p>}</Card></div><Card style={{ marginTop: 25 } as React.CSSProperties}><div className="row"><div><p className="eyebrow">Completion</p><h2>{complete ? "Topic complete" : "Ready when you are"}</h2></div><Button onClick={() => dispatch({ type: "toggleLearning", id: topicId })}>{complete ? "Mark incomplete" : "Complete topic"}</Button></div></Card></>; }
