"use client";

import dynamic from "next/dynamic";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { BarChart3, BookOpenCheck, BriefcaseBusiness, FileSearch, Menu, ShieldCheck, Sparkles, X } from "lucide-react";
import { ButtonLink, Card, Progress } from "@/components/ui/primitives";

const CareerGlobe = dynamic(() => import("./career-globe"), { ssr: false, loading: () => <div className="globe-loading">Loading opportunity map…</div> });
const journey = [{ title: "Resume", text: "Bring your real experience into one reusable candidate profile." },{ title: "Analysis", text: "Review extraction before a deterministic, explainable match score." },{ title: "Interview", text: "Practise questions grounded in your resume and target role." },{ title: "Learning", text: "Turn verified gaps into an ordered, trackable path." },{ title: "Jobs", text: "See why a role fits and which resume version was compared." }];

export function LandingPage() {
  const [open, setOpen] = useState(false);
  return <>
    <nav className="marketing-nav" aria-label="Primary"><div className="container nav-inner"><Link className="brand" href="/"><Image src="/brand/logo-mark.svg" width={40} height={40} alt="" />Career Copilot</Link><div className="nav-links"><a href="#journey">How it works</a><a href="#modules">Features</a><Link href="/sign-in">Sign in</Link><ButtonLink href="/sign-up">Get started</ButtonLink></div><button className="icon-button mobile-menu-button" onClick={() => setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation">{open ? <X /> : <Menu />}</button></div></nav>
    {open && <div className="mobile-drawer"><a href="#journey" onClick={() => setOpen(false)}>How it works</a><a href="#modules" onClick={() => setOpen(false)}>Features</a><Link href="/sign-in">Sign in</Link><ButtonLink href="/sign-up">Get started</ButtonLink></div>}
    <main id="main-content">
      <section className="container hero"><div className="hero-copy"><span className="badge badge-info">One profile. Every next step.</span><h1>Build the career profile employers are looking for.</h1><p>Analyse your resume, practise realistic interviews, close skill gaps, and discover opportunities through one connected career workspace.</p><div className="cluster"><ButtonLink href="/sign-up">Build my career profile</ButtonLink><ButtonLink href="/resume-analysis/report/demo" variant="secondary">Explore a sample report</ButtonLink></div><p className="hero-note"><ShieldCheck size={16} aria-hidden /> Demo data is clearly marked. You approve every resume change.</p></div><div className="globe-frame"><CareerGlobe /><div className="job-preview"><span className="badge badge-success">88% match</span><h3>Product Analyst</h3><p>Northstar Labs · Bengaluru</p></div></div></section>
      <section id="journey" className="section"><div className="container"><p className="eyebrow">A connected career journey</p><h2>Each decision improves the next one.</h2><div className="journey">{journey.map((item, index) => <article key={item.title}><span className="mono">0{index + 1}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>
      <section className="section"><div className="container grid-2"><div><p className="eyebrow">Evidence before advice</p><h2>Know exactly what the result is based on.</h2><p>Career Copilot separates extracted facts, deterministic matching, AI explanation, and suggested improvements. Missing text is never presented as proof that you lack a skill.</p><div className="stack"><div className="cluster"><span className="badge badge-success">Extracted fact</span><span className="badge badge-info">Deterministic result</span><span className="badge badge-ai">AI explanation</span></div><Card className="panel-blue"><div className="row"><strong>Requirement: Advanced SQL</strong><span className="badge badge-success">Strong match</span></div><p>Resume evidence: “Built cohort and retention analysis using window functions.”</p></Card></div></div><div className="preview-shell"><aside className="preview-side"><strong>Career Copilot</strong><p>Dashboard</p><p>Resume Analysis</p><p>Mock Interview</p><p>Learning Path</p><p>Recommended Jobs</p></aside><div className="preview-main"><p className="eyebrow">Readiness overview</p><div className="grid-2"><Card><span className="mono">ATS alignment</span><p className="metric-value">78<small>/100</small></p></Card><Card><span className="mono">Relevant roles</span><p className="metric-value">12</p></Card></div><Card className="mt-5"><Progress value={72} label="Interview readiness" /><br /><Progress value={41} label="Learning path" /></Card></div></div></div></section>
      <section id="modules" className="section"><div className="container"><p className="eyebrow">The workspace</p><h2>Four modules, one candidate context.</h2><div className="module-stripe"><FileSearch size={64} aria-hidden /><div><h3>Resume intelligence</h3><p>Review structured extraction, understand score contribution, and decide which evidence-based rewrites belong in the next version.</p></div></div><div className="module-stripe"><div><h3>Interview practice</h3><p>Configure targeted sessions, use safe browser media controls, and review technical and communication feedback without psychological claims.</p></div><BarChart3 size={64} aria-hidden /></div><div className="module-stripe"><BookOpenCheck size={64} aria-hidden /><div><h3>Learning paths</h3><p>Work through ordered resources connected to a specific ATS or interview gap.</p></div></div><div className="module-stripe"><div><h3>Job discovery</h3><p>Filter sample roles and inspect evidence-backed match explanations before saving a job.</p></div><BriefcaseBusiness size={64} aria-hidden /></div></div></section>
      <section className="section"><div className="container panel panel-blue row"><div><Sparkles size={36} aria-hidden /><h2>Make the next career move evidence-led.</h2><p>Start with your profile. Keep every result connected.</p></div><ButtonLink href="/sign-up">Create demo account</ButtonLink></div></section>
    </main><footer className="footer"><div className="container row"><div><div className="brand"><Image src="/brand/logo-mark.svg" width={38} height={38} alt="" />Career Copilot</div><p>Career preparation without black-box claims.</p></div><div className="cluster"><Link href="/resume-analysis">Product</Link><Link href="/settings/privacy">Privacy</Link><Link href="/sign-in">Sign in</Link><Link href="/sign-up">Create account</Link></div></div></footer>
  </>;
}
