"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useState } from "react";
import { Download, LogOut, Shield, Trash2 } from "lucide-react";
import { Badge, Button, Card, Input, PageHeader, Progress, Textarea } from "@/components/ui/primitives";
import { resetDemo, useDemo } from "@/providers/demo-provider";

const tabs = [["/settings/profile","Profile"],["/settings/account","Account"],["/settings/preferences","Preferences"],["/settings/privacy","Privacy"]];
function SettingsFrame({ children, title, description }: { children: React.ReactNode; title: string; description: string }) { const pathname = usePathname(); return <><PageHeader eyebrow="Settings" title={title} description={description}/><nav className="settings-nav" aria-label="Settings sections">{tabs.map(([href,label]) => <Link key={href} className={`button ${pathname === href ? "button-primary" : "button-secondary"}`} href={href} aria-current={pathname === href ? "page" : undefined}>{label}</Link>)}</nav>{children}</>; }

export function ProfileSettings() { const { state, dispatch } = useDemo(); const [saved,setSaved] = useState(false); const [draft,setDraft] = useState(state.candidate); return <SettingsFrame title="Candidate profile" description="This context powers every recommendation and report."><div className="grid-2"><Card className="stack"><div className="row"><div className="avatar" style={{ width: 72, height: 72, fontSize: 24 }}>AM</div><div><h2>{draft.name}</h2><Badge tone="success">82% complete</Badge></div></div><Progress value={82} label="Profile completion"/><label className="field-label">Full name<Input value={draft.name} onChange={(e)=>setDraft({...draft,name:e.target.value})}/></label><label className="field-label">Headline<Input value={draft.headline} onChange={(e)=>setDraft({...draft,headline:e.target.value})}/></label><label className="field-label">Bio<Textarea defaultValue="I use product data to clarify decisions and communicate practical trade-offs."/></label><label className="field-label">Email<Input type="email" value={draft.email} onChange={(e)=>setDraft({...draft,email:e.target.value})}/></label><label className="field-label">Phone<Input defaultValue="+91 98765 43210"/></label><label className="field-label">Location<Input value={draft.location} onChange={(e)=>setDraft({...draft,location:e.target.value})}/></label></Card><Card className="stack"><h2>Career context</h2><label className="field-label">Current role<Input value={draft.role} onChange={(e)=>setDraft({...draft,role:e.target.value})}/></label><label className="field-label">Experience<Input value={draft.experience} onChange={(e)=>setDraft({...draft,experience:e.target.value})}/></label><label className="field-label">Skills<Input value={draft.skills.join(", ")} onChange={(e)=>setDraft({...draft,skills:e.target.value.split(",").map(x=>x.trim())})}/></label><label className="field-label">Target roles<Input defaultValue="Senior Product Analyst, Growth Analyst"/></label><label className="field-label">Career goals<Textarea defaultValue="Lead evidence-based product decisions and mentor analysts."/></label><label className="field-label">Social links<Input defaultValue="linkedin.com/in/aarav-mehta"/></label><label className="field-label">Resume library<select className="field"><option>Product Analyst Resume v3.pdf</option><option>Product Analyst Resume v2.pdf</option></select></label><Button onClick={()=>{dispatch({type:"candidate",value:draft});setSaved(true)}}>Save profile</Button>{saved&&<p role="status" className="badge badge-success">Profile saved</p>}</Card></div></SettingsFrame>; }

export function AccountSettings() { const router=useRouter(); const {dispatch}=useDemo(); const [confirm,setConfirm]=useState<"delete"|"logout"|null>(null); return <SettingsFrame title="Account & access" description="Manage sign-in surfaces and demo data actions."><div className="grid-2"><Card className="stack"><h2>Security</h2><label className="field-label">Email<Input defaultValue="aarav@example.com" type="email"/></label><Button variant="secondary">Change password</Button><div className="suggestion"><strong>Google connection</strong><span>Not connected · UI placeholder</span></div><div className="suggestion"><strong>LinkedIn connection</strong><span>Not connected · UI placeholder</span></div><div className="suggestion"><strong>Two-factor authentication</strong><span>Roadmap state · unavailable</span></div></Card><Card className="stack"><h2>Account actions</h2><Button variant="secondary"><Download size={18}/>Export demo data</Button><Button variant="secondary" onClick={()=>setConfirm("logout")}><LogOut size={18}/>Logout</Button><Button variant="danger" onClick={()=>setConfirm("delete")}><Trash2 size={18}/>Delete demo account</Button><p>Destructive actions always require confirmation.</p></Card></div>{confirm&&<div role="dialog" aria-modal="true" aria-labelledby="confirm-title" className="panel" style={{position:"fixed",inset:"50% auto auto 50%",transform:"translate(-50%,-50%)",zIndex:100,width:"min(440px,calc(100% - 32px))"}}><h2 id="confirm-title">Confirm {confirm === "delete" ? "account deletion" : "logout"}</h2><p>{confirm === "delete" ? "This clears locally stored demo state. It does not contact a backend." : "You will return to the public landing page."}</p><div className="cluster"><Button variant="secondary" autoFocus onClick={()=>setConfirm(null)}>Cancel</Button><Button variant={confirm === "delete" ? "danger" : "primary"} onClick={()=>{dispatch({type:"patch",value:{authenticated:false}});router.push("/")}}>Confirm</Button></div></div>}</SettingsFrame>; }

export function PreferenceSettings() { const {state,dispatch}=useDemo(); return <SettingsFrame title="Experience preferences" description="Control motion, notifications, language, and reminders."><Card className="stack"><div className="row"><div><h2>Theme</h2><p>Light Blue is the active product theme for this phase.</p></div><Badge tone="info">Light Blue</Badge></div><label className="row"><span><strong>Reduced motion</strong><br/><small>Use short fades and stop automatic globe rotation.</small></span><input type="checkbox" checked={state.reducedMotion} onChange={(e)=>dispatch({type:"patch",value:{reducedMotion:e.target.checked}})}/></label>{["Email notifications","Job alerts","Learning reminders","Interview reminders"].map((label)=><label key={label} className="row"><span>{label}</span><input type="checkbox" defaultChecked={label!=="Job alerts"}/></label>)}<div className="grid-2"><label className="field-label">Language<select className="field"><option>English</option></select></label><label className="field-label">Time zone<select className="field"><option>Asia/Kolkata</option></select></label></div></Card></SettingsFrame>; }

export function PrivacySettings() { const {dispatch}=useDemo(); const [confirm,setConfirm]=useState(false); return <SettingsFrame title="Privacy controls" description="Decide which browser capabilities and demo records this workspace may use."><div className="grid-2"><Card className="stack"><Shield size={36}/><h2>Permissions</h2>{["Camera permissions","Microphone permissions","Resume-data permission","Job-recommendation consent","Profile visibility"].map((label)=><label key={label} className="row"><span>{label}</span><select className="field" style={{width:150}}><option>Ask</option><option>Allowed</option><option>Disabled</option></select></label>)}<label className="field-label">Recording retention<select className="field"><option>Do not retain</option><option>Until session ends</option></select></label></Card><Card className="stack"><h2>Stored demo data</h2><p>Career Copilot stores demo authentication, profile, learning progress, saved jobs, and suggestion decisions in this browser only.</p><Button variant="danger" onClick={()=>setConfirm(true)}><Trash2 size={18}/>Clear stored demo data</Button>{confirm&&<div role="dialog" aria-modal="true" aria-label="Confirm clear stored demo data" className="suggestion"><strong>Clear all demo state?</strong><p>This cannot be undone in this browser.</p><div className="cluster"><Button variant="secondary" onClick={()=>setConfirm(false)}>Cancel</Button><Button variant="danger" onClick={()=>{resetDemo(dispatch);setConfirm(false)}}>Clear data</Button></div></div>}</Card></div></SettingsFrame>; }
