"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useState } from "react";
import { MailCheck } from "lucide-react";
import { Button, Input } from "@/components/ui/primitives";
import { createClient } from "@/lib/supabase/client";

function Shell({ children, title, description }: { children: React.ReactNode; title: string; description: string }) {
  return <main id="main-content" className="auth-shell"><aside className="auth-aside"><Link className="brand" href="/"><Image src="/brand/logo-mark.svg" width={42} height={42} alt="" />Career Copilot</Link><div><p className="eyebrow">One connected workspace</p><h1>{title}</h1><p>{description}</p></div></aside><section className="auth-main">{children}</section></main>;
}

function configurationError() { return "Supabase is not configured. Copy .env.example to .env.local and add newly rotated public project values."; }

export function SignInScreen() {
  const router = useRouter(); const search = useSearchParams(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(search.get("error") === "configuration_required" ? configurationError() : ""); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); const supabase = createClient(); if (!supabase) return setError(configurationError()); setBusy(true); setError(""); const result = await supabase.auth.signInWithPassword({ email, password }); setBusy(false); if (result.error) return setError(result.error.message); router.replace(search.get("next") || "/dashboard"); router.refresh(); }
  async function oauth(provider: "google" | "linkedin_oidc") { const supabase = createClient(); if (!supabase) return setError(configurationError()); const { error: oauthError } = await supabase.auth.signInWithOAuth({ provider, options: { redirectTo: `${location.origin}/auth/callback` } }); if (oauthError) setError(oauthError.message); }
  return <Shell title="Welcome back to your career workspace." description="Your career records remain tied to your verified account."><form className="auth-card panel stack" onSubmit={submit}><div><p className="eyebrow">Secure sign in</p><h1>Sign in</h1></div><label className="field-label">Email<Input type="email" autoComplete="email" required value={email} onChange={(e) => setEmail(e.target.value)} /></label><label className="field-label">Password<Input type="password" autoComplete="current-password" required minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} /></label>{error && <p role="alert" className="field-error">{error}</p>}<div className="row"><span /><Link href="/forgot-password">Forgot password?</Link></div><Button disabled={busy} type="submit">{busy ? "Signing in…" : "Sign in"}</Button><div className="auth-divider">or</div><div className="grid-2"><Button type="button" variant="secondary" onClick={() => oauth("google")}>Continue with Google</Button><Button type="button" variant="secondary" onClick={() => oauth("linkedin_oidc")}>Continue with LinkedIn</Button></div><p>New here? <Link href="/sign-up"><strong>Create an account</strong></Link></p></form></Shell>;
}

export function SignUpScreen() {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState(""); const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (password !== confirm) return setError("Passwords do not match."); const supabase = createClient(); if (!supabase) return setError(configurationError()); setBusy(true); setError(""); const result = await supabase.auth.signUp({ email, password, options: { data: { full_name: name }, emailRedirectTo: `${location.origin}/auth/callback?next=/onboarding` } }); setBusy(false); if (result.error) return setError(result.error.message); setSent(true); }
  return <Shell title="Start with evidence you control." description="Your records are private by default and can be reviewed before they power another workflow.">{sent ? <div className="auth-card panel empty-state"><MailCheck size={44}/><h1>Check your inbox</h1><p>Use the verification link sent by Supabase to activate your account.</p></div> : <form className="auth-card panel stack" onSubmit={submit}><p className="eyebrow">Create account</p><h1>Get started</h1><label className="field-label">Full name<Input required minLength={2} value={name} onChange={(e) => setName(e.target.value)} /></label><label className="field-label">Email<Input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} /></label><label className="field-label">Password<Input type="password" autoComplete="new-password" required minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} /></label><label className="field-label">Confirm password<Input type="password" autoComplete="new-password" required value={confirm} onChange={(e) => setConfirm(e.target.value)} /></label>{error && <p role="alert" className="field-error">{error}</p>}<Button disabled={busy} type="submit">{busy ? "Creating account…" : "Create account"}</Button><p>Already registered? <Link href="/sign-in"><strong>Sign in</strong></Link></p></form>}</Shell>;
}

export function VerifyEmailScreen() { return <Shell title="Confirm your email." description="Account verification is handled by Supabase Auth."><div className="auth-card panel empty-state"><MailCheck size={44}/><h1>Check your inbox</h1><p>Open the verification link to continue. If it expired, return to sign up and request a new message.</p><Link className="button button-secondary" href="/sign-in">Back to sign in</Link></div></Shell>; }

export function PasswordScreen({ reset = false }: { reset?: boolean }) {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); const supabase = createClient(); if (!supabase) return setError(configurationError()); setError(""); if (reset) { if (password !== confirm) return setError("Passwords do not match."); const result = await supabase.auth.updateUser({ password }); if (result.error) return setError(result.error.message); router.replace("/dashboard"); router.refresh(); } else { const result = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${location.origin}/auth/callback?next=/reset-password` }); if (result.error) return setError(result.error.message); setMessage("If the address is registered, a recovery link has been sent."); } }
  return <Shell title="Recover your workspace." description="Recovery links and password changes are handled by Supabase Auth."><form className="auth-card panel stack" onSubmit={submit}><h1>{reset ? "Choose a new password" : "Reset your password"}</h1>{reset ? <><label className="field-label">New password<Input type="password" required minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} /></label><label className="field-label">Confirm password<Input type="password" required value={confirm} onChange={(e) => setConfirm(e.target.value)} /></label></> : <label className="field-label">Email<Input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} /></label>}{error && <p role="alert" className="field-error">{error}</p>}{message && <p role="status" className="badge badge-success">{message}</p>}<Button type="submit">{reset ? "Update password" : "Send reset link"}</Button></form></Shell>;
}
