"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useForm, useWatch } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Eye, EyeOff, MailCheck } from "lucide-react";
import { z } from "zod";
import { Button, Input } from "@/components/ui/primitives";
import { useDemo } from "@/providers/demo-provider";

const signInSchema = z.object({ email: z.string().email("Enter a valid email address"), password: z.string().min(8, "Password must contain at least 8 characters") });
const signUpSchema = z.object({ name: z.string().min(2, "Enter your full name"), email: z.string().email("Enter a valid email address"), password: z.string().min(8, "Use at least 8 characters").regex(/[A-Z]/, "Add an uppercase letter").regex(/[0-9]/, "Add a number"), confirm: z.string(), terms: z.literal(true, { error: "Accept the terms to continue" }) }).refine((v) => v.password === v.confirm, { path: ["confirm"], message: "Passwords do not match" });
type SignInValues = z.infer<typeof signInSchema>;
type SignUpValues = z.infer<typeof signUpSchema>;

function Shell({ children, title, description }: { children: React.ReactNode; title: string; description: string }) {
  return <main id="main-content" className="auth-shell"><aside className="auth-aside"><Link className="brand" href="/"><Image src="/brand/logo-mark.svg" width={42} height={42} alt="" />Career Copilot</Link><div><p className="eyebrow">One connected workspace</p><h1>{title}</h1><p>{description}</p></div></aside><section className="auth-main">{children}</section></main>;
}

export function SignInScreen() {
  const router = useRouter(); const { dispatch } = useDemo(); const [show, setShow] = useState(false);
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<SignInValues>({ resolver: zodResolver(signInSchema), defaultValues: { email: "aarav@example.com", password: "DemoPass1" } });
  return <Shell title="Welcome back to your career workspace." description="Your resume evidence, practice history, learning progress, and saved roles stay connected."><form className="auth-card panel stack" onSubmit={handleSubmit(() => { dispatch({ type: "patch", value: { authenticated: true } }); router.push("/dashboard"); })} noValidate><div><p className="eyebrow">Demo sign in</p><h1>Sign in</h1><p>Use the prefilled demo credentials or any valid email and password.</p></div><label className="field-label">Email<Input type="email" autoComplete="email" {...register("email")} aria-invalid={!!errors.email} aria-describedby="email-error" /></label>{errors.email && <p id="email-error" className="field-error">{errors.email.message}</p>}<label className="field-label">Password<div className="row"><Input type={show ? "text" : "password"} autoComplete="current-password" {...register("password")} aria-invalid={!!errors.password} /><button type="button" className="icon-button" onClick={() => setShow(!show)} aria-label={show ? "Hide password" : "Show password"}>{show ? <EyeOff /> : <Eye />}</button></div></label>{errors.password && <p className="field-error">{errors.password.message}</p>}<div className="row"><label className="cluster"><input type="checkbox" /> Remember me</label><Link href="/forgot-password">Forgot password?</Link></div><Button disabled={isSubmitting} type="submit">{isSubmitting ? "Signing in…" : "Sign in"}</Button><div className="auth-divider">or</div><div className="grid-2"><Button type="button" variant="secondary">G Google</Button><Button type="button" variant="secondary">in LinkedIn</Button></div><p>New here? <Link href="/sign-up"><strong>Create an account</strong></Link></p></form></Shell>;
}

export function SignUpScreen() {
  const router = useRouter(); const { dispatch } = useDemo(); const [show, setShow] = useState(false);
  const { register, handleSubmit, control, formState: { errors } } = useForm<SignUpValues>({ resolver: zodResolver(signUpSchema), defaultValues: { terms: false as true } }); const password = useWatch({ control, name: "password", defaultValue: "" }); const strength = [password.length >= 8, /[A-Z]/.test(password), /[0-9]/.test(password)].filter(Boolean).length;
  return <Shell title="Start with evidence you control." description="Build a connected demo profile, review every extracted field, and approve every suggested resume change."><form className="auth-card panel stack" onSubmit={handleSubmit((values) => { dispatch({ type: "candidate", value: { name: values.name, email: values.email } }); router.push("/verify-email"); })} noValidate><div><p className="eyebrow">Create demo account</p><h1>Get started</h1></div><label className="field-label">Full name<Input {...register("name")} aria-invalid={!!errors.name} /></label>{errors.name && <p className="field-error">{errors.name.message}</p>}<label className="field-label">Email<Input type="email" {...register("email")} aria-invalid={!!errors.email} /></label>{errors.email && <p className="field-error">{errors.email.message}</p>}<label className="field-label">Password<div className="row"><Input type={show ? "text" : "password"} {...register("password")} aria-invalid={!!errors.password} /><button type="button" className="icon-button" onClick={() => setShow(!show)} aria-label={show ? "Hide password" : "Show password"}>{show ? <EyeOff /> : <Eye />}</button></div></label><div className="progress" role="meter" aria-label="Password strength" aria-valuenow={strength} aria-valuemin={0} aria-valuemax={3}><span style={{ width: `${strength / 3 * 100}%` }} /></div>{errors.password && <p className="field-error">{errors.password.message}</p>}<label className="field-label">Confirm password<Input type="password" {...register("confirm")} aria-invalid={!!errors.confirm} /></label>{errors.confirm && <p className="field-error">{errors.confirm.message}</p>}<label className="cluster"><input type="checkbox" {...register("terms")} /> I agree to the demo terms and privacy notice.</label>{errors.terms && <p className="field-error">{errors.terms.message}</p>}<Button type="submit">Create account</Button><p>Already have an account? <Link href="/sign-in"><strong>Sign in</strong></Link></p></form></Shell>;
}

export function VerifyEmailScreen() { const router = useRouter(); return <Shell title="One quick confirmation." description="This demo does not send email. Use the visible verification action to continue."><div className="auth-card panel empty-state"><MailCheck size={44} /><h1>Check your inbox</h1><p>Demo mode: no message was sent. Confirm the sample address to continue.</p><Button onClick={() => router.push("/sign-in")}>Verify demo email</Button></div></Shell>; }

export function PasswordScreen({ reset = false }: { reset?: boolean }) { const [done, setDone] = useState(false); return <Shell title="Get back to your workspace." description="A complete recovery UI, isolated from any real email or identity service."><form className="auth-card panel stack" onSubmit={(e) => { e.preventDefault(); setDone(true); }}>{done ? <><MailCheck size={44} /><h1>{reset ? "Password updated" : "Reset link prepared"}</h1><p>{reset ? "Your demo password has been updated." : "Demo mode: no email was sent. Continue to the reset screen."}</p><Link className="button button-primary" href={reset ? "/sign-in" : "/reset-password"}>Continue</Link></> : <><p className="eyebrow">Account recovery</p><h1>{reset ? "Choose a new password" : "Reset your password"}</h1>{reset ? <><label className="field-label">New password<Input type="password" required minLength={8} /></label><label className="field-label">Confirm password<Input type="password" required minLength={8} /></label></> : <label className="field-label">Email<Input type="email" required /></label>}<Button type="submit">{reset ? "Update password" : "Prepare reset link"}</Button></>}</form></Shell>; }
