"use client";

import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import { Check, FileUp, X } from "lucide-react";
import { Button, Card, Input, PageHeader } from "@/components/ui/primitives";
import { completionScore, isValidCareerFile } from "@/lib/utils";
import { useDemo } from "@/providers/demo-provider";

const steps = ["Basic information", "Career information", "Work preferences", "Skills & education", "Resume upload", "Review"];
export function Onboarding() {
  const router = useRouter(); const { state, dispatch } = useDemo(); const [step, setStep] = useState(0); const [error, setError] = useState(""); const [file, setFile] = useState<File | null>(null); const [draft, setDraft] = useState({ name: state.candidate.name, headline: state.candidate.headline, email: state.candidate.email, phone: "", location: state.candidate.location, role: state.candidate.role, experience: state.candidate.experience, target: "Senior Product Analyst", preference: "Hybrid", skills: state.candidate.skills.join(", "), education: "B.Tech, Information Technology" });
  const completion = useMemo(() => completionScore(Object.values(draft)), [draft]); const update = (key: string, value: string) => setDraft((v) => ({ ...v, [key]: value }));
  const next = () => { if (step === 0 && (!draft.name || !draft.email)) { setError("Name and email are required."); return; } setError(""); setStep((v) => Math.min(5, v + 1)); };
  const finish = () => { dispatch({ type: "candidate", value: { name: draft.name, email: draft.email, headline: draft.headline, location: draft.location, role: draft.role, experience: draft.experience, skills: draft.skills.split(",").map((x) => x.trim()).filter(Boolean) } }); dispatch({ type: "patch", value: { authenticated: true, onboardingComplete: true, activeResume: file?.name || state.activeResume } }); router.push("/dashboard"); };
  return <main id="main-content" className="section"><div className="container"><PageHeader eyebrow="Candidate onboarding" title={steps[step]} description="Build one shared profile for resume analysis, interviews, learning, and jobs." action={<div className="panel"><strong>{completion}%</strong><p>Profile complete</p></div>} /><div className="steps" aria-label={`Step ${step + 1} of ${steps.length}`}>{steps.map((_, i) => <span key={i} className={`step ${i <= step ? "done" : ""}`} />)}</div><Card>
    {step === 0 && <div className="grid-2"><label className="field-label">Full name<Input value={draft.name} onChange={(e) => update("name", e.target.value)} /></label><label className="field-label">Email<Input type="email" value={draft.email} onChange={(e) => update("email", e.target.value)} /></label><label className="field-label">Professional headline<Input value={draft.headline} onChange={(e) => update("headline", e.target.value)} /></label><label className="field-label">Phone<Input value={draft.phone} onChange={(e) => update("phone", e.target.value)} /></label><label className="field-label">Location<Input value={draft.location} onChange={(e) => update("location", e.target.value)} /></label></div>}
    {step === 1 && <div className="grid-2"><label className="field-label">Current role<Input value={draft.role} onChange={(e) => update("role", e.target.value)} /></label><label className="field-label">Experience<Input value={draft.experience} onChange={(e) => update("experience", e.target.value)} /></label><label className="field-label">Target role<Input value={draft.target} onChange={(e) => update("target", e.target.value)} /></label><label className="field-label">Career goal<Input defaultValue="Lead product decisions with reliable analysis" /></label></div>}
    {step === 2 && <div className="grid-2"><label className="field-label">Work mode<select className="field" value={draft.preference} onChange={(e) => update("preference", e.target.value)}><option>Remote</option><option>Hybrid</option><option>On-site</option></select></label><label className="field-label">Preferred locations<Input defaultValue="Bengaluru, Singapore" /></label><label className="field-label">Employment type<select className="field"><option>Full-time</option><option>Contract</option></select></label><label className="field-label">Notice period<Input defaultValue="30 days" /></label></div>}
    {step === 3 && <div className="grid-2"><label className="field-label">Skills<Input value={draft.skills} onChange={(e) => update("skills", e.target.value)} /></label><label className="field-label">Education<Input value={draft.education} onChange={(e) => update("education", e.target.value)} /></label><label className="field-label">LinkedIn<Input placeholder="https://linkedin.com/in/…" /></label><label className="field-label">Portfolio<Input placeholder="https://…" /></label></div>}
    {step === 4 && <div><label className="dropzone"><FileUp size={42} /><strong>{file ? file.name : "Drop a PDF or DOCX resume here"}</strong><span>Maximum size: 10 MB</span><Input className="sr-only" type="file" accept=".pdf,.docx" onChange={(e) => { const selected = e.target.files?.[0]; if (!selected) return; if (!isValidCareerFile(selected)) { setError("Choose a PDF or DOCX file no larger than 10 MB."); setFile(null); } else { setError(""); setFile(selected); } }} /></label>{file && <Button variant="quiet" onClick={() => setFile(null)}><X size={17} />Remove file</Button>}</div>}
    {step === 5 && <div className="grid-2"><div><p className="eyebrow">Profile</p><h2>{draft.name}</h2><p>{draft.headline}</p><p>{draft.location} · {draft.experience}</p></div><div className="stack"><div className="row"><span>Target role</span><strong>{draft.target}</strong></div><div className="row"><span>Work mode</span><strong>{draft.preference}</strong></div><div className="row"><span>Resume</span><strong>{file?.name || "Use demo resume"}</strong></div><div className="row"><span>Ready</span><Check /></div></div></div>}
    {error && <p role="alert" className="field-error">{error}</p>}<div className="row" style={{ marginTop: 28 }}><Button variant="secondary" disabled={step === 0} onClick={() => setStep((v) => Math.max(0, v - 1))}>Previous</Button><div className="cluster"><Button variant="quiet" onClick={() => router.push("/dashboard")}>Save & continue later</Button>{step < 5 ? <Button onClick={next}>Next</Button> : <Button onClick={finish}>Complete profile</Button>}</div></div>
  </Card></div></main>;
}
