"use client";

import { useMemo, useState } from "react";
import { Bookmark, BookmarkCheck, ExternalLink, MapPin, Search } from "lucide-react";
import { Badge, Button, ButtonLink, Card, EmptyState, Input, PageHeader, Progress } from "@/components/ui/primitives";
import { jobs } from "@/data/demo-data";
import { useDemo } from "@/providers/demo-provider";

export function JobsHome({ savedOnly = false }: { savedOnly?: boolean }) { const { state, dispatch } = useDemo(); const [query, setQuery] = useState(""); const [mode, setMode] = useState("All modes"); const [threshold, setThreshold] = useState("0"); const filtered = useMemo(() => jobs.filter((job) => (!savedOnly || state.savedJobs.includes(job.id)) && `${job.title} ${job.company} ${job.location}`.toLowerCase().includes(query.toLowerCase()) && (mode === "All modes" || job.mode === mode) && job.score >= Number(threshold)), [savedOnly, state.savedJobs, query, mode, threshold]);
  return <><PageHeader eyebrow={savedOnly ? "Saved roles" : "Job recommendations"} title={savedOnly ? "Roles you chose to revisit." : "Roles matched to visible resume evidence."} description="Every score explains the matched evidence, text not found in the selected resume, and resume version used." action={<ButtonLink href={savedOnly ? "/jobs" : "/jobs/saved"} variant="secondary">{savedOnly ? "All recommendations" : `Saved jobs (${state.savedJobs.length})`}</ButtonLink>} /><div className="filters"><label className="field-label">Search<div className="row"><Search size={18}/><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Role, company, location" /></div></label><label className="field-label">Work mode<select className="field" value={mode} onChange={(e) => setMode(e.target.value)}><option>All modes</option><option>Remote</option><option>Hybrid</option><option>On-site</option></select></label><label className="field-label">Match threshold<select className="field" value={threshold} onChange={(e) => setThreshold(e.target.value)}><option value="0">Any match</option><option value="75">75%+</option><option value="85">85%+</option></select></label><label className="field-label">Sort<select className="field"><option>Best match</option><option>Newest</option></select></label></div>{filtered.length === 0 ? <EmptyState title="No matching jobs" description="Adjust your filters or save a role from recommendations." href="/jobs" action="View recommendations"/> : <div className="grid-2">{filtered.map((job) => { const saved = state.savedJobs.includes(job.id); return <Card className="job-card" key={job.id}><div className="row"><div className="cluster"><div className="job-score" aria-label={`${job.score} percent match`}>{job.score}%</div><div><h2>{job.title}</h2><p>{job.company}</p></div></div><button className="icon-button" onClick={() => dispatch({ type: "toggleJob", id: job.id })} aria-label={saved ? `Unsave ${job.title}` : `Save ${job.title}`}>{saved ? <BookmarkCheck/> : <Bookmark/>}</button></div><div className="cluster"><span><MapPin size={15}/> {job.location}</span><Badge tone="info">{job.mode}</Badge><span>{job.posted}</span></div><div><strong>Matched skills</strong><p>{job.skills.join(" · ")}</p><strong>Not found in resume</strong><p>{job.missing.join(" · ")}</p></div><div className="row"><small>Basis: Product Analyst Resume v3</small><ButtonLink href={`/jobs/${job.id}`} variant="secondary">View details</ButtonLink></div></Card>; })}</div>}</>;
}

export function JobDetail({ jobId }: { jobId: string }) { const { state, dispatch } = useDemo(); const job = jobs.find((item) => item.id === jobId) || jobs[0]; const saved = state.savedJobs.includes(job.id); return <><PageHeader eyebrow="Job detail · Sample listing" title={job.title} description={`${job.company} · ${job.location} · ${job.mode}`} action={<Button onClick={() => dispatch({ type: "toggleJob", id: job.id })}>{saved ? <BookmarkCheck size={17}/> : <Bookmark size={17}/>} {saved ? "Saved" : "Save job"}</Button>} /><div className="grid-2"><Card><h2>Role summary</h2><p>Use product data to identify opportunities, measure experiments, and communicate recommendations to cross-functional partners.</p><h3>Responsibilities</h3><ul><li>Own recurring product analysis and KPI definitions.</li><li>Partner on experiment design and interpretation.</li><li>Translate findings into clear product decisions.</li></ul><h3>Original listing</h3><Button disabled variant="secondary"><ExternalLink size={17}/>Unavailable in frontend demo</Button></Card><Card className="panel-blue"><div className="cluster"><div className="score-ring">{job.score}</div><div><Badge tone="success">Strong match</Badge><h2>Why it matches</h2></div></div><div className="stack"><Progress value={91} label="Skills"/><Progress value={82} label="Experience"/><Progress value={76} label="Projects"/><Progress value={86} label="Education"/></div></Card></div><div className="grid-3" style={{ marginTop: 26 }}><Card><h3>Candidate strengths</h3><p>{job.skills.join(", ")} have direct resume evidence.</p></Card><Card><h3>Resume gaps</h3><p>{job.missing.join(", ")} was not found in the selected resume.</p></Card><Card><h3>Suggested learning</h3><p>Practise product experiment interpretation and tool-specific workflows.</p></Card></div><div className="cluster" style={{ marginTop: 26 }}><ButtonLink href="/resume-analysis/new">Analyse resume</ButtonLink><ButtonLink href="/mock-interview/setup" variant="secondary">Practise interview</ButtonLink></div></>; }
